# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/chat_app.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15Protos/chat_app.proto\"\'\n\x04\x43hat\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2/\n\x0b\x43hatService\x12 \n\nChatStream\x12\x05.Chat\x1a\x05.Chat\"\x00(\x01\x30\x01\x42\n\xaa\x02\x07\x43hatAppb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.chat_app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007ChatApp'
  _globals['_CHAT']._serialized_start=25
  _globals['_CHAT']._serialized_end=64
  _globals['_CHATSERVICE']._serialized_start=66
  _globals['_CHATSERVICE']._serialized_end=113
# @@protoc_insertion_point(module_scope)
