# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat_app.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\007ChatApp',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63hat_app.proto\"\'\n\x04\x43hat\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2/\n\x0b\x43hatService\x12 \n\nChatStream\x12\x05.Chat\x1a\x05.Chat\"\x00(\x01\x30\x01\x42\n\xaa\x02\x07\x43hatAppb\x06proto3'
)




_CHAT = _descriptor.Descriptor(
  name='Chat',
  full_name='Chat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='Chat.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='Chat.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['Chat'] = _CHAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chat = _reflection.GeneratedProtocolMessageType('Chat', (_message.Message,), {
  'DESCRIPTOR' : _CHAT,
  '__module__' : 'chat_app_pb2'
  # @@protoc_insertion_point(class_scope:Chat)
  })
_sym_db.RegisterMessage(Chat)


DESCRIPTOR._options = None

_CHATSERVICE = _descriptor.ServiceDescriptor(
  name='ChatService',
  full_name='ChatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=59,
  serialized_end=106,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='ChatService.ChatStream',
    index=0,
    containing_service=None,
    input_type=_CHAT,
    output_type=_CHAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVICE)

DESCRIPTOR.services_by_name['ChatService'] = _CHATSERVICE

# @@protoc_insertion_point(module_scope)
